<?php
	class Errors{
		const URL_NOT_FULL =601;
		const UNDEFINE_CLASS =602;
		const UNDEFINE_METHOD =603;
		const REGISTER_FAIL =604;
		
		const ACCOUNT_NOT_NULL =605;
		const PASS_NOT_NULL =606;
	
		const PHONE_FORMAT_ERROR =607;
		const MAIL_FORMAT_ERROR =608;
		const CODE_NOT_NULL =609;
		const CODE_ERROR =610;
		const USER_EXIST =611;
		const USER_NOT_EXIST =612;
		const PHONE_MAIL_NOT_NULL =613;
		const USER_OR_PASS_ERROR =614;
		
		const TOKEN_NOT_NULL =615;
		const TOKEN_EXPIRED =616;
		const TOKEN_FAIL =617;
		const TOKEN_UPTIME_FAIL =618;
		
		const PICTURE_NOT_NULL =619;
		const TITLE_NOT_NULL =620;
		const CONTENT_NOT_NULL =621;
		const ADD_PRODUCT_FAIL =622;
		const PRODUCTID_NOT_NULL =623;
		const DEL_PRODUCT_FAIL =624;
		const UPD_PRODUCT_FAIL =625;
		
		const PAGE_NOT_NULL =626;
		const PAGE_LIMIT_NOT_NULL =627;
		const SERACH_SOURCE_NOT_EXIST =628;
	}
?>